[build]
  command = "npm run build:ssr"
  publish = "dist/kind-of-magic-fe/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-ssr"
  status = 200
